package com.code.challenge.domain.common

enum class ResourceType {
  LOADING,
  SUCCESS,
  ERROR,
  VALIDATION_ERROR,
  EMPTY_DATA,
  CONNECTION_ERROR,
  ERROR_MESSAGE,
  UNAUTHORIZED_ERROR,
  BAD_REQUEST_ERROR,
  NOT_ACTIVATED_ERROR,
  UNKNOWN_ERROR,
  FORBIDDEN_ERROR,
  NOT_ENOUGH_BALANCE,
  NOT_FOUND
}